name: recommended-project
recipe: lamp
composer_version: 2.2
config:
  webroot: web
services:
  appserver:
    type: php:8.1
    xdebug: false
    config:
      php: .lando/php.ini
    ssl: true
    build_as_root:
      - apt-get update -y
      - apt-get install vim -y
      - composer install --dev
  database:
    type: mysql:5.7
    creds:
      user: lamp
      password: lamp
      database: lamp
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    build:
      - npm install
    globals:
      gulp-cli: latest
      webpack: latest
      npm: latest
tooling:
  npm:
    service: node
  node:
    service: appserver
  gulp:
    service: node
  webpack:
    service: node
  yarn:
    service: node
  drush:
    service: appserver